apiVersion: v1
kind: Pod
metadata:
  name: firefox-pod
  labels:
    app: firefox
  namespace: my-namespace
spec:
  containers:
    - name: firefox
      image: linuxserver/firefox

      ports:
        - containerPort: 3000

      env:
        - name: USER_ID
          value: "1000"

        - name: GROUP_ID
          value: "1000"

      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"

        limits:
          cpu: "500m"
          memory: "512Mi"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: firefox
#   namespace: my-namespace
# spec:
#   selector:
#     app: firefox
#   ports:
#     - port: 3000
#       targetPort: 3000
#   type: ClusterIP