apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-dynamic

provisioner: disk.csi.azure.com

parameters:
  skuName: Premium_LRS
  kind: managed

reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true