apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: azure-disk-dynamic

  resources:
    requests:
      storage: 5Gi