apiVersion: v1
kind: PersistentVolume

metadata:
  name: azurefile-pv

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: azurefile-static

  azureFile:
    secretName: mysecrete
    shareName: myshare
    readonly: false