apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod

spec:
  containers:
    - name: nginx
      image: nginx:latest

      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "2"
          memory: "512Mi"

      volumeMounts:
        - name: ebs-volume
          mountPath: /data

  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-pvc
 