apiVersion: v1
kind: Pod
metadata:
  name: dbeaver-pod
  namespace: my-namespace

spec:
  containers:
    - name: dbeaver
      image: dbeaver/cloudbeaver:latest

      ports:
        - containerPort: 8978

      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"

        limits:
          cpu: "500m"
          memory: "512Mi"