apiVersion: v1
kind: Pod
metadata:
  name: firefox-pod
  labels:
    app: firefox
  namespace: my-namespace
spec:
  containers:
    - name: firefox
      image: linuxserver/firefox

      ports:
        - containerPort: 3000

      env:
        - name: USER_ID
          value: "1000"

        - name: GROUP_ID
          value: "1000"

